# Use root/example as user/password credentials
version: '3.1'

services:
  gameback_front:
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    env_file:
      - ./local.env
    ports:
      - 3000:3000

